### ISSUE TITLE
DCGAN model not aligned with the paper

### ISSUE THREAD

**Issue by ZakariaeBelmekki98** [aldelb/non-verbal-behaviours-generation#1]
Hi, it seems to me that the deep conditional GAN implementation located in the directory (CGAN/model) does not correspond to the architecture described in the paper (page 7). I do not see the upsampling and downsampling operations. I

**Comment by aldelb** [comment]
Hi, there is no Upsampling or Downsampling operation in the CGAN model (you drew my attention to a mistake in the document, which mentions a maxPool. I'm sorry, this is not the case, but the model does correspond to the diagram on page 7). However there is in the AED model on page 8, which you'll find in the model/AED section of the github. You can find a new version of this work on this github: https://github.com/aldelb/non_verbal_facial_animation. 
I hope I've answered your question. Have a nice day!

**Comment by ZakariaeBelmekki98** [comment]
Hi, thank you very much for your answer! That's helpful. I have another question, I will open another issue for it for practicality purposes. Cheers!
