### ISSUE TITLE
CGAN implementation: forward pass size reshaping

### ISSUE THREAD

**Issue by ZakariaeBelmekki98** [aldelb/non-verbal-behaviours-generation#2]
Hi, just a question about the forward pass in the CGAN's discriminator. I don't understand why the input is reshaped into (bs * lt, -1). I might be wrong but it seems to me that it might entangle the input information. Take the following example.

`x = torch.arange(0, 5)`
`x = x.view(1, 1, -1)`
`x = x.repeat(1, 3, 1)`

To use the paper's notations, we get a tensor with a batch size of 1, a window size of 3 and 5 features numbered from 0 to 4 (included). Doing the following

`
x = x.view(1 * 5, -1)
`

would result in the following tensor 
`
tensor([[0, 1, 2],
              [3, 4, 0],
              [1, 2, 3],
              [4, 0, 1],
              [2, 3, 4]])
`
If we pass that to the model, wouldn't it learn a mapping for this entangled form instead of the original one where rows are independent in the axis of features (but not the temporal one of course). I hope I'm clear. Thanks in advance!

**Comment by aldelb** [comment]
Hi, 

This reshape representation was only passed to a part of the model for linear layers, not for double conv, GRU or LSTM. We were inspired by another state-of-the-art model to create this CGAN model.  However, we were indeed reticent to use reshaping during the training of the model. This is one of the reasons why the AED structures on this github or on the new one ([link](https://github.com/aldelb/non_verbal_facial_animation)) do not contain any.

**Comment by ZakariaeBelmekki98** [comment]
Hi, okay I see. Thank you very much for your answer! I wanted to implement a purely adversarial model without the autoencoder component to see if GAN alone is able to generate data. I think I should explore AED. Cheers!
